[package]
name = "cml-chain-json-schema-gen"
version = "5.2.0"
edition = "2018"
keywords = ["cardano"]

[dependencies]
serde_json = "1.0.57"
schemars = "0.8.8"
cml-chain = { path = "../../rust" }
cml-crypto = { path = "../../../crypto/rust" }
